// Code generated by MockGen. DO NOT EDIT.
// Source: replication.go
//
// Generated by this command:
//
//	mockgen -destination=../service/mocks/replication_mock.go -package=mocks -source=replication.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/anthanhphan/go-distributed-file-storage/internal/storage/domain"
	shard "github.com/anthanhphan/go-distributed-file-storage/pkg/shard"
	gomock "go.uber.org/mock/gomock"
)

// MockReplicationPort is a mock of ReplicationPort interface.
type MockReplicationPort struct {
	ctrl     *gomock.Controller
	recorder *MockReplicationPortMockRecorder
	isgomock struct{}
}

// MockReplicationPortMockRecorder is the mock recorder for MockReplicationPort.
type MockReplicationPortMockRecorder struct {
	mock *MockReplicationPort
}

// NewMockReplicationPort creates a new mock instance.
func NewMockReplicationPort(ctrl *gomock.Controller) *MockReplicationPort {
	mock := &MockReplicationPort{ctrl: ctrl}
	mock.recorder = &MockReplicationPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReplicationPort) EXPECT() *MockReplicationPortMockRecorder {
	return m.recorder
}

// FetchChunk mocks base method.
func (m *MockReplicationPort) FetchChunk(ctx context.Context, targetAddr, chunkID string) (uint32, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchChunk", ctx, targetAddr, chunkID)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchChunk indicates an expected call of FetchChunk.
func (mr *MockReplicationPortMockRecorder) FetchChunk(ctx, targetAddr, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchChunk", reflect.TypeOf((*MockReplicationPort)(nil).FetchChunk), ctx, targetAddr, chunkID)
}

// GetMerkleNodes mocks base method.
func (m *MockReplicationPort) GetMerkleNodes(ctx context.Context, targetAddr string, indices []int32) ([]shard.MerkleNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleNodes", ctx, targetAddr, indices)
	ret0, _ := ret[0].([]shard.MerkleNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerkleNodes indicates an expected call of GetMerkleNodes.
func (mr *MockReplicationPortMockRecorder) GetMerkleNodes(ctx, targetAddr, indices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleNodes", reflect.TypeOf((*MockReplicationPort)(nil).GetMerkleNodes), ctx, targetAddr, indices)
}

// GetMerkleRoot mocks base method.
func (m *MockReplicationPort) GetMerkleRoot(ctx context.Context, targetAddr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleRoot", ctx, targetAddr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerkleRoot indicates an expected call of GetMerkleRoot.
func (mr *MockReplicationPortMockRecorder) GetMerkleRoot(ctx, targetAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleRoot", reflect.TypeOf((*MockReplicationPort)(nil).GetMerkleRoot), ctx, targetAddr)
}

// ListItemsInBucket mocks base method.
func (m *MockReplicationPort) ListItemsInBucket(ctx context.Context, targetAddr string, bucketID int32) ([]shard.BucketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsInBucket", ctx, targetAddr, bucketID)
	ret0, _ := ret[0].([]shard.BucketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsInBucket indicates an expected call of ListItemsInBucket.
func (mr *MockReplicationPortMockRecorder) ListItemsInBucket(ctx, targetAddr, bucketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsInBucket", reflect.TypeOf((*MockReplicationPort)(nil).ListItemsInBucket), ctx, targetAddr, bucketID)
}

// ReplicateChunk mocks base method.
func (m *MockReplicationPort) ReplicateChunk(ctx context.Context, target shard.Node, chunk domain.Chunk) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicateChunk", ctx, target, chunk)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateChunk indicates an expected call of ReplicateChunk.
func (mr *MockReplicationPortMockRecorder) ReplicateChunk(ctx, target, chunk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicateChunk", reflect.TypeOf((*MockReplicationPort)(nil).ReplicateChunk), ctx, target, chunk)
}
