// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -destination=../service/mocks/storage_mock.go -package=mocks -source=storage.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/anthanhphan/go-distributed-file-storage/internal/storage/domain"
	shard "github.com/anthanhphan/go-distributed-file-storage/pkg/shard"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// Compact mocks base method.
func (m *MockStorageRepository) Compact() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact")
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockStorageRepositoryMockRecorder) Compact() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockStorageRepository)(nil).Compact))
}

// DeleteChunk mocks base method.
func (m *MockStorageRepository) DeleteChunk(ctx context.Context, id domain.ChunkID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChunk", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteChunk indicates an expected call of DeleteChunk.
func (mr *MockStorageRepositoryMockRecorder) DeleteChunk(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChunk", reflect.TypeOf((*MockStorageRepository)(nil).DeleteChunk), ctx, id)
}

// GetMerkleNodes mocks base method.
func (m *MockStorageRepository) GetMerkleNodes(indices []int32) ([]shard.MerkleNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleNodes", indices)
	ret0, _ := ret[0].([]shard.MerkleNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMerkleNodes indicates an expected call of GetMerkleNodes.
func (mr *MockStorageRepositoryMockRecorder) GetMerkleNodes(indices any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleNodes", reflect.TypeOf((*MockStorageRepository)(nil).GetMerkleNodes), indices)
}

// GetMerkleRoot mocks base method.
func (m *MockStorageRepository) GetMerkleRoot() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleRoot")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMerkleRoot indicates an expected call of GetMerkleRoot.
func (mr *MockStorageRepositoryMockRecorder) GetMerkleRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleRoot", reflect.TypeOf((*MockStorageRepository)(nil).GetMerkleRoot))
}

// GetParentID mocks base method.
func (m *MockStorageRepository) GetParentID(id domain.ChunkID) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetParentID", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetParentID indicates an expected call of GetParentID.
func (mr *MockStorageRepositoryMockRecorder) GetParentID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetParentID", reflect.TypeOf((*MockStorageRepository)(nil).GetParentID), id)
}

// HasChunk mocks base method.
func (m *MockStorageRepository) HasChunk(ctx context.Context, id domain.ChunkID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasChunk", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasChunk indicates an expected call of HasChunk.
func (mr *MockStorageRepositoryMockRecorder) HasChunk(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasChunk", reflect.TypeOf((*MockStorageRepository)(nil).HasChunk), ctx, id)
}

// ListAllKeys mocks base method.
func (m *MockStorageRepository) ListAllKeys() []domain.ChunkID {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllKeys")
	ret0, _ := ret[0].([]domain.ChunkID)
	return ret0
}

// ListAllKeys indicates an expected call of ListAllKeys.
func (mr *MockStorageRepositoryMockRecorder) ListAllKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllKeys", reflect.TypeOf((*MockStorageRepository)(nil).ListAllKeys))
}

// ListItemsInBucket mocks base method.
func (m *MockStorageRepository) ListItemsInBucket(ctx context.Context, bucketID int32) ([]shard.BucketItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsInBucket", ctx, bucketID)
	ret0, _ := ret[0].([]shard.BucketItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsInBucket indicates an expected call of ListItemsInBucket.
func (mr *MockStorageRepositoryMockRecorder) ListItemsInBucket(ctx, bucketID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsInBucket", reflect.TypeOf((*MockStorageRepository)(nil).ListItemsInBucket), ctx, bucketID)
}

// ReadChunk mocks base method.
func (m *MockStorageRepository) ReadChunk(ctx context.Context, id domain.ChunkID) (uint32, io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadChunk", ctx, id)
	ret0, _ := ret[0].(uint32)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReadChunk indicates an expected call of ReadChunk.
func (mr *MockStorageRepositoryMockRecorder) ReadChunk(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadChunk", reflect.TypeOf((*MockStorageRepository)(nil).ReadChunk), ctx, id)
}

// WriteChunk mocks base method.
func (m *MockStorageRepository) WriteChunk(ctx context.Context, id domain.ChunkID, parentID string, checksum uint32, reader io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteChunk", ctx, id, parentID, checksum, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteChunk indicates an expected call of WriteChunk.
func (mr *MockStorageRepositoryMockRecorder) WriteChunk(ctx, id, parentID, checksum, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteChunk", reflect.TypeOf((*MockStorageRepository)(nil).WriteChunk), ctx, id, parentID, checksum, reader)
}
