// Code generated by MockGen. DO NOT EDIT.
// Source: upload_service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/dependencies_mock.go -package=mocks -source=upload_service.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockChunkReplicator is a mock of ChunkReplicator interface.
type MockChunkReplicator struct {
	ctrl     *gomock.Controller
	recorder *MockChunkReplicatorMockRecorder
	isgomock struct{}
}

// MockChunkReplicatorMockRecorder is the mock recorder for MockChunkReplicator.
type MockChunkReplicatorMockRecorder struct {
	mock *MockChunkReplicator
}

// NewMockChunkReplicator creates a new mock instance.
func NewMockChunkReplicator(ctrl *gomock.Controller) *MockChunkReplicator {
	mock := &MockChunkReplicator{ctrl: ctrl}
	mock.recorder = &MockChunkReplicatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChunkReplicator) EXPECT() *MockChunkReplicatorMockRecorder {
	return m.recorder
}

// ReplicateChunk mocks base method.
func (m *MockChunkReplicator) ReplicateChunk(ctx context.Context, fileID string, chunkIndex int, chunkData []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplicateChunk", ctx, fileID, chunkIndex, chunkData)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateChunk indicates an expected call of ReplicateChunk.
func (mr *MockChunkReplicatorMockRecorder) ReplicateChunk(ctx, fileID, chunkIndex, chunkData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplicateChunk", reflect.TypeOf((*MockChunkReplicator)(nil).ReplicateChunk), ctx, fileID, chunkIndex, chunkData)
}

// MockMetadataPersistence is a mock of MetadataPersistence interface.
type MockMetadataPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataPersistenceMockRecorder
	isgomock struct{}
}

// MockMetadataPersistenceMockRecorder is the mock recorder for MockMetadataPersistence.
type MockMetadataPersistenceMockRecorder struct {
	mock *MockMetadataPersistence
}

// NewMockMetadataPersistence creates a new mock instance.
func NewMockMetadataPersistence(ctrl *gomock.Controller) *MockMetadataPersistence {
	mock := &MockMetadataPersistence{ctrl: ctrl}
	mock.recorder = &MockMetadataPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataPersistence) EXPECT() *MockMetadataPersistenceMockRecorder {
	return m.recorder
}

// SaveMetadata mocks base method.
func (m *MockMetadataPersistence) SaveMetadata(ctx context.Context, metaID string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetadata", ctx, metaID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMetadata indicates an expected call of SaveMetadata.
func (mr *MockMetadataPersistenceMockRecorder) SaveMetadata(ctx, metaID, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetadata", reflect.TypeOf((*MockMetadataPersistence)(nil).SaveMetadata), ctx, metaID, data)
}

// MockIDGenerator is a mock of IDGenerator interface.
type MockIDGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockIDGeneratorMockRecorder
	isgomock struct{}
}

// MockIDGeneratorMockRecorder is the mock recorder for MockIDGenerator.
type MockIDGeneratorMockRecorder struct {
	mock *MockIDGenerator
}

// NewMockIDGenerator creates a new mock instance.
func NewMockIDGenerator(ctrl *gomock.Controller) *MockIDGenerator {
	mock := &MockIDGenerator{ctrl: ctrl}
	mock.recorder = &MockIDGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDGenerator) EXPECT() *MockIDGeneratorMockRecorder {
	return m.recorder
}

// Next mocks base method.
func (m *MockIDGenerator) Next() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Next indicates an expected call of Next.
func (mr *MockIDGeneratorMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockIDGenerator)(nil).Next))
}
