// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -destination=../service/mocks/storage_node_mock.go -package=mocks -source=repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	storagev1 "github.com/anthanhphan/go-distributed-file-storage/proto/gen/storage/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageNode is a mock of StorageNode interface.
type MockStorageNode struct {
	ctrl     *gomock.Controller
	recorder *MockStorageNodeMockRecorder
	isgomock struct{}
}

// MockStorageNodeMockRecorder is the mock recorder for MockStorageNode.
type MockStorageNodeMockRecorder struct {
	mock *MockStorageNode
}

// NewMockStorageNode creates a new mock instance.
func NewMockStorageNode(ctrl *gomock.Controller) *MockStorageNode {
	mock := &MockStorageNode{ctrl: ctrl}
	mock.recorder = &MockStorageNodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageNode) EXPECT() *MockStorageNodeMockRecorder {
	return m.recorder
}

// DeleteChunk mocks base method.
func (m *MockStorageNode) DeleteChunk(ctx context.Context, addr, chunkID string) (*storagev1.DeleteChunkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteChunk", ctx, addr, chunkID)
	ret0, _ := ret[0].(*storagev1.DeleteChunkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteChunk indicates an expected call of DeleteChunk.
func (mr *MockStorageNodeMockRecorder) DeleteChunk(ctx, addr, chunkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteChunk", reflect.TypeOf((*MockStorageNode)(nil).DeleteChunk), ctx, addr, chunkID)
}

// ReadChunk mocks base method.
func (m *MockStorageNode) ReadChunk(ctx context.Context, addr, chunkID string, writer io.Writer) (*storagev1.ReadChunkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadChunk", ctx, addr, chunkID, writer)
	ret0, _ := ret[0].(*storagev1.ReadChunkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadChunk indicates an expected call of ReadChunk.
func (mr *MockStorageNodeMockRecorder) ReadChunk(ctx, addr, chunkID, writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadChunk", reflect.TypeOf((*MockStorageNode)(nil).ReadChunk), ctx, addr, chunkID, writer)
}

// WriteChunk mocks base method.
func (m *MockStorageNode) WriteChunk(ctx context.Context, addr, chunkID, parentID string, checksum uint32, reader io.Reader) (*storagev1.WriteChunkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteChunk", ctx, addr, chunkID, parentID, checksum, reader)
	ret0, _ := ret[0].(*storagev1.WriteChunkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteChunk indicates an expected call of WriteChunk.
func (mr *MockStorageNodeMockRecorder) WriteChunk(ctx, addr, chunkID, parentID, checksum, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteChunk", reflect.TypeOf((*MockStorageNode)(nil).WriteChunk), ctx, addr, chunkID, parentID, checksum, reader)
}
